import { ICaptionsControlProps } from "../interface/captions";

export const NONE_PRESET: ICaptionsControlProps = {
  id: "caption-none",
  appearedColor: "#ffffff",
  activeColor: "#ffffff",
  activeFillColor: "transparent",
  color: "#ffffff",
  backgroundColor: "transparent",
  borderColor: "transparent",
  borderWidth: 0,
  boxShadow: { color: "#ffffff", x: 15, y: 15, blur: 60 },
};

export const CAPTION_PRESETS: ICaptionsControlProps[] = [
  // {
  //   id: "caption-1",
  //   appearedColor: "#FFFFFF",
  //   activeColor: "#50FF12",
  //   activeFillColor: "#7E12FF",
  //   color: "#DADADA",
  //   isKeywordColor: "transparent",
  //   backgroundColor: "transparent",
  //   borderColor: "#000000",
  //   borderWidth: 5,
  //   fontFamily: "Poppins-Bold",
  //   fontUrl: "https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7V1tvFP-KUEg.ttf",
  //   previewUrlDynamic: "https://cdn.designcombo.dev/caption_previews/dynamic-preset1.webm",
  //   previewUrlStatic: "https://cdn.designcombo.dev/caption_previews/static-preset1.png",
  // },
  // {
  //   id: "caption-2",
  //   appearedColor: "#000000",
  //   activeColor: "#000000",
  //   activeFillColor: "transparent",
  //   color: "#b5b5b8",
  //   isKeywordColor: "transparent",
  //   backgroundColor: "#e6e6e5",
  //   borderColor: "transparent",
  //   borderWidth: 0,
  //   fontFamily: "Poppins-Bold",
  //   fontUrl: "https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7V1tvFP-KUEg.ttf",
  //   previewUrlDynamic: "https://cdn.designcombo.dev/caption_previews/dynamic-preset2.webm",
  //   previewUrlStatic: "https://cdn.designcombo.dev/caption_previews/static-preset2.png",
  // },
  // {
  //   id: "caption-3",
  //   appearedColor: "#ffffff",
  //   activeColor: "#ffffff",
  //   activeFillColor: "transparent",
  //   isKeywordColor: "transparent",
  //   color: "#ffffff",
  //   backgroundColor: "transparent",
  //   borderColor: "#000000",
  //   borderWidth: 10,
  //   boxShadow: { color: "#ffffff", x: 15, y: 15, blur: 60 },
  //   previewUrlDynamic: "https://cdn.designcombo.dev/caption_previews/dynamic-preset3.webm",
  //   previewUrlStatic: "https://cdn.designcombo.dev/caption_previews/static-preset3.png",
  // },
  // {
  //   id: "caption-4",
  //   appearedColor: "#ffffff",
  //   activeColor: "#ffffff",
  //   activeFillColor: "transparent",
  //   color: "transparent",
  //   backgroundColor: "transparent",
  //   borderColor: "#ffffff",
  //   borderWidth: 5,
  //   boxShadow: { color: "#ffffff", x: 15, y: 15, blur: 60 },
  //   fontFamily: "ChelseaMarket-Regular",
  //   fontUrl:
  //     "https://fonts.gstatic.com/s/chelseamarket/v8/BCawqZsHqfr89WNP_IApC8tzKBhlLA4uKkWk.ttf",
  //   previewUrlDynamic: "https://cdn.designcombo.dev/caption_previews/dynamic-preset5.webm",
  //   previewUrlStatic: "https://cdn.designcombo.dev/caption_previews/static-preset5.png",
  // },
  // {
  //   id: "caption-5",
  //   appearedColor: "#ffffff",
  //   activeColor: "#ffffff",
  //   activeFillColor: "#fc5a05",
  //   color: "#ffffff",
  //   isKeywordColor: "transparent",
  //   backgroundColor: "transparent",
  //   borderColor: "#000000",
  //   borderWidth: 5,
  //   previewUrlDynamic: "https://cdn.designcombo.dev/caption_previews/dynamic-preset6.webm",
  //   previewUrlStatic: "https://cdn.designcombo.dev/caption_previews/static-preset6.png",
  // },
  {
    id: "caption-6",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    fontFamily: "Roboto-Black",
    type: "word",
    fontUrl: "https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf",
    previewUrlDynamic: "https://cdn.designcombo.dev/caption_previews/dynamic-preset18.webm",
    previewUrlStatic: "https://cdn.designcombo.dev/caption_previews/static-preset18.png",
  },
  {
    id: "caption-7",
    appearedColor: "#000000",
    activeColor: "#000000",
    activeFillColor: "transparent",
    color: "#000000",
    isKeywordColor: "transparent",
    backgroundColor: "#ffffff",
    borderColor: "transparent",
    borderWidth: 0,
    fontSize: 64,
    textBoxStyle: {
      style: "tiktok",
      textAlign: "center",
      maxLines: 2,
      borderRadius: 16,
      horizontalPadding: 48,
      verticalPadding: 16,
    },
    fontFamily: "Proxima-Nova",
    fontUrl: "https://cdn.subgen.co/FONTS/proxima-nova-semibold.ttf",
    previewUrlDynamic: "https://cdn.designcombo.dev/caption_previews/dynamic-preset2.webm",
    previewUrlStatic: "https://cdn.designcombo.dev/caption_previews/static-preset2.png",
  },
];
