export const TEXT_PRESETS = [
  {
    type: "Text",
    name: "Classic Bold",
    text: "Title",
    style: {
      fontSize: 96,
      fontFamily: "Roboto-Bold",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl: "https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf",
      color: "#ffffff",
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 240,
      y: 898,
      width: 590,
      height: 109,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-5.png",
    },
  },
  {
    type: "Text",
    name: "Simple Badge",
    text: "Simple",
    style: {
      fontSize: 48,
      fontFamily: "Montserrat-Bold",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl: "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_dJE7g7J_950vCo.ttf",
      color: "#080808",
      background: {
        color: "#FFFFFF",
        paddingY: 12,
        paddingX: 24,
      },
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 240,
      y: 898,
      width: 590,
      height: 109,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-1.png",
    },
  },
  {
    type: "Text",
    name: "Elegant Serif",
    text: "Serif",
    style: {
      fontSize: 48,
      fontFamily: "PTSerif-Bold",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl: "https://fonts.gstatic.com/s/ptserif/v12/EJRSQgYoZZY2vCFuvAnt65qVXSr3pNNB.ttf",
      color: "#ffffff",
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 248,
      y: 895,
      width: 582,
      height: 192,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-4.png",
    },
  },
  {
    type: "Text",
    name: "Monospace",
    text: "Typewriter",
    style: {
      fontSize: 48,
      fontFamily: "SourceCodePro-Bold",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl:
        "https://fonts.gstatic.com/s/sourcecodepro/v18/HI_diYsKILxRpg3hIP6sJ7fM7PqPMcMnZFqUwX28DCuXhM5hTXUcdJg.ttf",
      color: "#ffffff",
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 248,
      y: 895,
      width: 582,
      height: 192,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-3.png",
    },
  },
  {
    type: "Text",
    name: "Poppins Bold",
    text: "Bold",
    style: {
      fontSize: 96,
      fontFamily: "Poppins-Bold",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl: "https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7V1tvFP-KUEg.ttf",
      color: "#ffffff",
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 245,
      y: 864,
      width: 582,
      height: 192,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-2.png",
    },
  },

  {
    type: "Text",
    name: "Abril Elegant",
    text: "Elegant",
    style: {
      fontSize: 96,
      fontFamily: "AbrilFatface-Regular",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl:
        "https://fonts.gstatic.com/s/abrilfatface/v12/zOL64pLDlL1D99S8g8PtiKchm-BsjOLhZBY.ttf",
      color: "#ffffff",
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 240,
      y: 898,
      width: 590,
      height: 192,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-9.png",
    },
  },
  {
    type: "Text",
    name: "Modern Sora",
    text: "Modern",
    style: {
      fontSize: 96,
      fontFamily: "Sora-Light",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl: "https://fonts.gstatic.com/s/sora/v3/xMQOuFFYT72X5wkB_18qmnndmScMnn-KIwNhBti0.ttf",
      color: "#ffffff",
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 240,
      y: 898,
      width: 590,
      height: 192,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-10.png",
    },
  },

  {
    type: "Text",
    name: "Classic Sans",
    text: "Classic",
    style: {
      fontSize: 96,
      fontFamily: "WorkSans-Regular",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl:
        "https://fonts.gstatic.com/s/worksans/v13/QGY_z_wNahGAdqQ43RhVcIgYT2Xz5u32K0nXNigDp6_cOyA.ttf",
      color: "#ffffff",
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 240,
      y: 898,
      width: 590,
      height: 192,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-6.png",
    },
  },
  {
    type: "Text",
    name: "Industrial Display",
    text: "INDUSTRIAL",
    style: {
      fontSize: 96,
      fontFamily: "BigShouldersDisplay-Bold",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl:
        "https://fonts.gstatic.com/s/bigshouldersdisplay/v6/fC1MPZJEZG-e9gHhdI4-NBbfd2ys3SjJCx12wPgf9g-_3F0YdWg8JF46SRP4yZQ.ttf",
      color: "#ffffff",
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 240,
      y: 898,
      width: 590,
      height: 192,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-8.png",
    },
  },
  {
    type: "Text",
    name: "Reliable Bold",
    text: "Reliable",
    style: {
      fontSize: 96,
      fontFamily: "WorkSans-Bold",
      fontWeight: "normal",
      fontStyle: "normal",
      align: "center",
      wordWrap: true,
      wordWrapWidth: 600,
      fontUrl:
        "https://fonts.gstatic.com/s/worksans/v13/QGY_z_wNahGAdqQ43RhVcIgYT2Xz5u32K67QNigDp6_cOyA.ttf",
      color: "#ffffff",
    },
    timing: {
      display: { from: 0, to: 5000000 },
      trim: { from: 0, to: 5000000 },
      duration: 5000000,
      playbackRate: 1,
    },
    transform: {
      x: 240,
      y: 898,
      width: 590,
      height: 192,
      angle: 0,
      opacity: 1,
      zIndex: 10,
    },
    metadata: {
      previewUrl: "https://cdn.scenify.io/text-preset-preview/preset-text-7.png",
    },
  },
] as const;
