import { ICaptionsControlProps } from "../interface/captions";

export const NONE_PRESET: ICaptionsControlProps = {
  appearedColor: "#ffffff",
  activeColor: "#ffffff",
  activeFillColor: "transparent",
  color: "#ffffff",
  backgroundColor: "transparent",
  borderColor: "transparent",
  borderWidth: 0,
  boxShadow: { color: "#ffffff", x: 15, y: 15, blur: 60 },
};

export const STYLE_CAPTION_PRESETS: ICaptionsControlProps[] = [
  {
    appearedColor: "#FFFFFF",
    activeColor: "#50FF12",
    activeFillColor: "#7E12FF",
    color: "#DADADA",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 5,
    fontFamily: "Bangers-Regular",
    isKeywordColor: "#000000",
    fontUrl:
      "https://fonts.gstatic.com/s/bangers/v13/FeVQS0BTqb0h60ACL5la2bxii28.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset1.webm",
  },
  {
    appearedColor: "#000000",
    activeColor: "#000000",
    activeFillColor: "transparent",
    color: "#b5b5b8",
    backgroundColor: "#e6e6e5",
    borderColor: "transparent",
    borderWidth: 0,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset2.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    boxShadow: { color: "#ffffff", x: 15, y: 15, blur: 60 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset3.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#ffffff",
    borderWidth: 5,
    boxShadow: { color: "#ffffff", x: 15, y: 15, blur: 60 },
    fontFamily: "ChelseaMarket-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/chelseamarket/v8/BCawqZsHqfr89WNP_IApC8tzKBhlLA4uKkWk.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset5.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#fc5a05",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 5,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset6.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    fontFamily: "Roboto-Black",
    type: "word",
    fontUrl:
      "https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset18.webm",
  },
  {
    appearedColor: "#EE1212",
    activeColor: "#EE1212",
    activeFillColor: "transparent",
    color: "#EE1212",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    fontFamily: "Roboto-Black",
    type: "word",
    animation: "popCaption",
    fontUrl:
      "https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset18.webm",
  },
  {
    appearedColor: "#fcbf03",
    activeColor: "#fcbf03",
    activeFillColor: "transparent",
    color: "#fcbf03",
    backgroundColor: "transparent",
    borderColor: "#fcbe03",
    borderWidth: 5,
    boxShadow: { color: "#fcbe03", x: 15, y: 15, blur: 60 },
    fontFamily: "CabinCondensed-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/cabincondensed/v14/nwpMtK6mNhBK2err_hqkYhHRqmwaYOjZ5HZl8Q.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset7.webm",
  },
  {
    appearedColor: "#fffd30",
    activeColor: "#fffd30",
    activeFillColor: "transparent",
    color: "#fffd30",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    boxShadow: { color: "#fffd30", x: 15, y: 15, blur: 60 },
    animation: "charTypewriter",
    fontFamily: "Chivo-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/chivo/v12/va9I4kzIxd1KFoBvS-J3kbDP.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset8.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    boxShadow: { color: "#161616", x: 15, y: 15, blur: 30 },
    animation: "scaleCaption",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset10.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    boxShadow: { color: "#ffffff", x: 15, y: 15, blur: 60 },
    animation: "popCaption",
    fontFamily: "Montserrat-SemiBold",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_bZF7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset12.webm",
  },
  {
    appearedColor: "#b5b5b8",
    activeColor: "#000000",
    activeFillColor: "transparent",
    color: "#b5b5b8",
    backgroundColor: "#e6e6e5",
    borderColor: "transparent",
    borderWidth: 0,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset13.webm",
  },
  {
    appearedColor: "#827a7f",
    activeColor: "#80eac9",
    activeFillColor: "transparent",
    color: "#827a7f",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 1 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset14.webm",
  },
  {
    appearedColor: "#ec41e2",
    activeColor: "#ec41e2",
    activeFillColor: "transparent",
    color: "#ec41e2",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "FjallaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fjallaone/v8/Yq6R-LCAWCX3-6Ky7FAFnOZwkxgtUb8.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset15.webm",
  },
  {
    appearedColor: "#b7bb62",
    activeColor: "#b7bb62",
    activeFillColor: "transparent",
    color: "#b7bb62",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "AnonymousPro-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/anonymouspro/v14/rP2Bp2a15UIB7Un-bOeISG3pLlw89CH98Ko.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset19.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    animation: "fadeCaption",
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 1 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset20.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#b5f026",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset21.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#cbc900",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 1 },
    fontFamily: "Roboto-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset22.webm",
  },
  {
    appearedColor: "#d30dbd",
    activeColor: "#d30dbd",
    activeFillColor: "transparent",
    color: "#e89161",
    backgroundColor: "#e4ff00",
    borderColor: "transparent",
    borderWidth: 0,
    fontFamily: "AnonymousPro-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/anonymouspro/v14/rP2Bp2a15UIB7Un-bOeISG3pLlw89CH98Ko.ttf",
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset23.webm",
  },
  {
    appearedColor: "#000000",
    activeColor: "#000000",
    activeFillColor: "transparent",
    color: "#000000",
    backgroundColor: "transparent",
    borderColor: "#ffffff",
    borderWidth: 5,
    boxShadow: { color: "#000000", x: 1, y: 1, blur: 4 },
    textTransform: "uppercase",
    fontFamily: "FrancoisOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/francoisone/v15/_Xmr-H4zszafZw3A-KPSZutNxgKQu_avAg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset25.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#8ffb9f",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset26.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7d0bdc",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 5,
    textTransform: "uppercase",
    boxShadow: { color: "#000000", x: 1, y: 1, blur: 4 },
    fontFamily: "FrancoisOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/francoisone/v15/_Xmr-H4zszafZw3A-KPSZutNxgKQu_avAg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset27.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#2f9bf4",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset28.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#16f3f8",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset29.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    animation: "fadeCaption",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset30.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7d0bdc",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    boxShadow: { color: "#000000", x: 2, y: 2, blur: 40 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset32.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#7d0bdc",
    borderColor: "transparent",
    borderWidth: 0,
    animation: "fadeCaption",
    fontFamily: "EncodeSans-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/encodesans/v8/LDIcapOFNxEwR-Bd1O9uYNmnUQomAgE25imKSbHhROjLsZBWTSrQGGHjZtWP7FJCt2c.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset33.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#d20604",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset34.webm",
  },
  {
    appearedColor: "#000000",
    activeColor: "#000000",
    activeFillColor: "transparent",
    color: "#000000",
    backgroundColor: "#f0ea00",
    borderColor: "transparent",
    borderWidth: 0,
    fontFamily: "AnonymousPro-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/anonymouspro/v14/rP2Bp2a15UIB7Un-bOeISG3pLlw89CH98Ko.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset35.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7d0bdc",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    textTransform: "uppercase",
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 1 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset36.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#f2e218",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 1 },
    textTransform: "uppercase",
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset37.webm",
  },
  {
    appearedColor: "#000000",
    activeColor: "#000000",
    activeFillColor: "transparent",
    color: "#000000",
    backgroundColor: "#e4ff00",
    borderColor: "transparent",
    borderWidth: 0,
    fontFamily: "AnonymousPro-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/anonymouspro/v14/rP2Bp2a15UIB7Un-bOeISG3pLlw89CH98Ko.ttf",
    textTransform: "uppercase",
    animation: "fadeByWord",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset38.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 10 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset39.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    animation: "scaleCaption",
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset40.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffe401",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset41.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#d769b3",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset43.webm",
  },
  {
    appearedColor: "#45efba",
    activeColor: "#45efba",
    activeFillColor: "#000000",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset45.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    textTransform: "uppercase",
    boxShadow: { color: "#000000", x: 15, y: 15, blur: 60 },
    fontFamily: "Knewave-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/knewave/v9/sykz-yx0lLcxQaSItSq9-trEvlQ.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset48.webm",
  },
  {
    appearedColor: "#ddd257",
    activeColor: "#ddd257",
    activeFillColor: "transparent",
    color: "#ddd257",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "AnonymousPro-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/anonymouspro/v14/rP2Bp2a15UIB7Un-bOeISG3pLlw89CH98Ko.ttf",
    textTransform: "uppercase",
    animation: "fadeCaption",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset49.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#85fc0e",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset50.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 2,
    textTransform: "uppercase",
    fontFamily: "FjallaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fjallaone/v8/Yq6R-LCAWCX3-6Ky7FAFnOZwkxgtUb8.ttf",
    boxShadow: { color: "#ffffff", x: 4, y: 4, blur: 60 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset52.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 2,
    animation: "fadeCaption",
    textTransform: "uppercase",
    fontFamily: "FjallaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fjallaone/v8/Yq6R-LCAWCX3-6Ky7FAFnOZwkxgtUb8.ttf",
    boxShadow: { color: "#ffffff", x: 4, y: 4, blur: 60 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset53.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#f70406",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    textTransform: "uppercase",
    fontFamily: "FjallaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fjallaone/v8/Yq6R-LCAWCX3-6Ky7FAFnOZwkxgtUb8.ttf",
    boxShadow: { color: "#ffffff", x: 4, y: 4, blur: 60 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset54.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "FjallaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fjallaone/v8/Yq6R-LCAWCX3-6Ky7FAFnOZwkxgtUb8.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset55.webm",
  },
  {
    type: "word",
    appearedColor: "#000000",
    activeColor: "#000000",
    activeFillColor: "#03f237",
    color: "#000000",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    animation: "fadeCaption",
    textTransform: "uppercase",
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    boxShadow: { color: "#ffffff", x: 4, y: 4, blur: 60 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset56.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#000000",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    fontFamily: "AnonymousPro-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/anonymouspro/v14/rP2Bp2a15UIB7Un-bOeISG3pLlw89CH98Ko.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset57.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    animation: "scaleMidCaption",
    textTransform: "uppercase",
    fontFamily: "PermanentMarker-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/permanentmarker/v10/Fh4uPib9Iyv2ucM6pGQMWimMp004HaqIfrT5nlk.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset58.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7d0bdc",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    textTransform: "uppercase",
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 60 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset59.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "Atma-SemiBold",
    fontUrl:
      "https://fonts.gstatic.com/s/atma/v8/uK_z4rqWc-Eoo7Z1Kjc9PvedRkM.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset60.webm",
  },
  {
    appearedColor: "#26ecea",
    activeColor: "#26ecea",
    activeFillColor: "transparent",
    color: "#26ecea",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset61.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#000000",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "AnonymousPro-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/anonymouspro/v14/rP2Bp2a15UIB7Un-bOeISG3pLlw89CH98Ko.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset64.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#000000",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset65.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#aef962",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    textTransform: "uppercase",
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset66.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#000000",
    borderColor: "transparent",
    borderWidth: 0,
    fontFamily: "AnonymousPro-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/anonymouspro/v14/rP2Bp2a15UIB7Un-bOeISG3pLlw89CH98Ko.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset67.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 15,
    animation: "scaleCaption",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset68.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#00cbd8",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 5,
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset69.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "AlfaSlabOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/alfaslabone/v10/6NUQ8FmMKwSEKjnm5-4v-4Jh6dVretWvYmE.ttf",
    animation: "fadeCaption",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset70.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "AnonymousPro-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/anonymouspro/v14/rP2Bp2a15UIB7Un-bOeISG3pLlw89CH98Ko.ttf",
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset71.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    animation: "scaleDownCaption",
    textTransform: "uppercase",
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 30 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset72.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#f9861a",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    textTransform: "uppercase",
    boxShadow: { color: "#000000", x: 10, y: 10, blur: 30 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset74.webm",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    textTransform: "uppercase",
    boxShadow: { color: "#ffffff", x: 4, y: 4, blur: 2 },
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset75.webm",
  },
  {
    type: "word",
    appearedColor: "#c2af38",
    activeColor: "#c2af38",
    activeFillColor: "transparent",
    color: "#c2af38",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    animation: "fadeCaption",
    textTransform: "uppercase",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset76.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#6c4df7",
    color: "#ffffff",
    backgroundColor: "#41434a",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset77.webm",
  },
  {
    type: "word",
    appearedColor: "#fff600",
    activeColor: "#fff600",
    activeFillColor: "transparent",
    color: "#fff600",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Imbue10pt-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/imbue/v9/RLpXK5P16Ki3fXhj5cvGrqjocPk4n-gVX3M93TnrnvhoP8iXfOsNNK-Q4xY.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset78.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#f6ff00",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Montserrat-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_dJE7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset80.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 28 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#d8c6b0",
    activeColor: "#d8c6b0",
    activeFillColor: "transparent",
    color: "#6b766e",
    backgroundColor: "#334744",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset81.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "AndadaPro-Medium",
    fontUrl:
      "https://fonts.gstatic.com/s/andadapro/v7/HhyEU5Qi9-SuOEhPe4LtKoVCuWGURPcg3DP7BY8cFLzvIt2S.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset83.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#00000049",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Poppins-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7V1tvFP-KUEg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset84.webm",
  },
  {
    appearedColor: "#00fef8",
    activeColor: "#00fef8",
    activeFillColor: "transparent",
    isKeywordColor: "#e03d1f",
    color: "#00fef8",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    textTransform: "uppercase",
    fontFamily: "BebasNeue-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/bebasneue/v2/JTUSjIg69CK48gW7PXooxW5rygbi49c.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset86.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#74f94b",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    textTransform: "uppercase",
    fontFamily: "Rubik-Black",
    fontUrl:
      "https://fonts.gstatic.com/s/rubik/v14/iJWZBXyIfDnIV5PNhY1KTN7Z-Yh-ro-1UE80V4bVkA.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset87.webm",
    animation: "captionAnimationKeyword4",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#f7ce46",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    textTransform: "uppercase",
    fontFamily: "Poppins-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7V1tvFP-KUEg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset88.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    textTransform: "uppercase",
    fontFamily: "Poppins-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7V1tvFP-KUEg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset89.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#ff0000",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SigmarOne-Regular", // "font Avenir Next"
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset90.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 100 },
  },
  {
    appearedColor: "#00fef8",
    activeColor: "#00fef8",
    activeFillColor: "transparent",
    isKeywordColor: "#ff311f",
    color: "#00fef8",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset92.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 30 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#62d57b",
    color: "#ffffff",
    backgroundColor: "#75fbfd",
    borderColor: "#000000",
    borderWidth: 3,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset93.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    animation: "upDownCaption",
  },
  {
    appearedColor: "#f8df25",
    activeColor: "#f8df25",
    activeFillColor: "transparent",
    color: "#f8df25",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "CabinCondensed-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/cabincondensed/v14/nwpMtK6mNhBK2err_hqkYhHRqmwaYOjZ5HZl8Q.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset95.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
  },
  {
    appearedColor: "#1e1b1b",
    activeColor: "#ff3c00",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "DMSans-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/dmsans/v6/rP2Cp2ywxg089UriASitOB-sClQX6Cg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset96.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#ffffff27",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "CabinCondensed-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/cabincondensed/v14/nwpJtK6mNhBK2err_hqkYhHRqmwi3Mf97F15-K1oqQ.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset97.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#e7ef4e",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    textAlign: "left",
    fontFamily: "BebasNeue-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/bebasneue/v2/JTUSjIg69CK48gW7PXooxW5rygbi49c.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset98.webm",
    animation: "fadeCaption",
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#f7ce46",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SigmarOne-Regular", // "font Avenir Next"
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset100.webm",
    animation: "upLeftCaption",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#6d7780",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Montserrat-Light",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_cJD7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset101.webm",
    animation: "upLeftCaption",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Inter-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset103.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffb0bd",
    activeFillColor: "transparent",
    isKeywordColor: "#ffd980",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#c95858",
    borderWidth: 5,
    fontFamily: "FredokaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fredokaone/v8/k3kUo8kEI-tA1RRcTZGmTmHBA6aF8Bf_.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset104.webm",
    boxShadow: { color: "#412424", x: 0, y: 0, blur: 60 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#93f9ff",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Lemonada-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/lemonada/v14/0QI-MXFD9oygTWy_R-FFlwV-bgfR7QJGnex2mfWc3Z2pTg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset105.webm",
    animation: "fadeByWord",
  },
  {
    type: "word",
    appearedColor: "#f5ec00",
    activeColor: "#f5ec00",
    activeFillColor: "transparent",
    color: "#f5ec00",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Bangers-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/bangers/v13/FeVQS0BTqb0h60ACL5la2bxii28.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset108.webm",
    boxShadow: { color: "#f7e848", x: 0, y: 0, blur: 60 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Montserrat-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_dJE7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset110.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    textTransform: "uppercase",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#e8a7bf",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "FredokaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fredokaone/v8/k3kUo8kEI-tA1RRcTZGmTmHBA6aF8Bf_.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset111.webm",
    boxShadow: { color: "#ff00bb", x: 0, y: 0, blur: 60 },
  },
  {
    appearedColor: "#f6ff00",
    activeColor: "#f6ff00",
    activeFillColor: "transparent",
    color: "#f6ff00",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Neuton-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/neuton/v13/UMBTrPtMoH62xUZyyII7civlBw.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset112.webm",
  },
  {
    type: "word",
    appearedColor: "#f6ff00",
    activeColor: "#f6ff00",
    activeFillColor: "transparent",
    color: "#f6ff00",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Montserrat-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_dJE7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset113.webm",
    textTransform: "uppercase",
    animation: "scaleDownCaption",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#e8a7bf",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Bangers-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/bangers/v13/FeVQS0BTqb0h60ACL5la2bxii28.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset114.webm",
    boxShadow: { color: "#ff00bb", x: 0, y: 0, blur: 60 },
  },
  {
    type: "word",
    appearedColor: "#e8d4b8",
    activeColor: "#e8d4b8",
    activeFillColor: "transparent",
    color: "#e8d4b8",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Inter-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset116.webm",
    animation: "fadeCaption",
    textTransform: "lowercase",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#d6ff42",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Lemonada-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/lemonada/v14/0QI-MXFD9oygTWy_R-FFlwV-bgfR7QJGnex2mfWc3Z2pTg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset117.webm",
    animation: "fadeCaption",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#f6bd60",
    activeFillColor: "transparent",
    isKeywordColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#f24b34",
    borderWidth: 5,
    fontFamily: "LilitaOne",
    fontUrl:
      "https://fonts.gstatic.com/s/lilitaone/v8/i7dPIFZ9Zz-WBtRtedDbUEZ2RFq7AwU.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset118.webm",
    boxShadow: { color: "#f24b34", x: 4, y: 2, blur: 1 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#f7ce46",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 5,
    fontFamily: "Inter-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset119.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    animation: "upDownCaption",
    textAlign: "right",
    preservedColorKeyWord: true,
    wordAnimation: {
      type: "scale",
      application: "active",
      mode: "static",
      value: 1.2,
    },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#fff994",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "BebasNeue-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/bebasneue/v2/JTUSjIg69CK48gW7PXooxW5rygbi49c.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset121.webm",
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 60 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 5,
    fontFamily: "Montserrat-Black",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_epG7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset122.webm",
    textTransform: "uppercase",
    wordAnimation: {
      type: "scale",
      application: "active",
      mode: "dynamic",
      value: 1.2,
    },
  },
  {
    type: "word",
    appearedColor: "#fff600",
    activeColor: "#fff600",
    activeFillColor: "transparent",
    color: "#fff600",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Bangers-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/bangers/v13/FeVQS0BTqb0h60ACL5la2bxii28.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset123.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    textTransform: "uppercase",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#f7ce46",
    color: "#ffffff",
    backgroundColor: "#731ef5",
    borderColor: "#000000",
    borderWidth: 3,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset125.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    animation: "upDownCaption",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff6e",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Inter-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset126.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#8d1bf5",
    color: "transparent",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderColor: "#000000",
    borderWidth: 3,
    fontFamily: "Inter-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset127.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    animation: "upDownCaption",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#15c7ff",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 3,
    fontFamily: "RobotoCondensed-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/robotocondensed/v19/ieVi2ZhZI2eCN5jzbjEETS9weq8-32meKCMSbvtdYyQ.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset128.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
    wordAnimation: {
      type: "scale",
      application: "active",
      mode: "dynamic",
      value: 1.2,
    },
  },

  {
    appearedColor: "#f7ce46",
    activeColor: "#f7ce46",
    activeFillColor: "transparent",
    isKeywordColor: "#15c7ff",
    color: "#f7ce46",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 3,
    fontFamily: "Rubik-Black",
    fontUrl:
      "https://fonts.gstatic.com/s/rubik/v14/iJWZBXyIfDnIV5PNhY1KTN7Z-Yh-ro-1UE80V4bVkA.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset129.webm",
    boxShadow: { color: "#eb4d3d", x: 4, y: 4, blur: 10 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "#1f8aff",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SigmarOne-Regular", // "font Avenir Next"
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset131.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 10 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#feff00",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "#000000",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "RobotoSlab-Medium",
    fontUrl:
      "https://fonts.gstatic.com/s/robotoslab/v16/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjovoSWaG5iddG-1A.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset132.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 10 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#ab9de9",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "FredokaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fredokaone/v8/k3kUo8kEI-tA1RRcTZGmTmHBA6aF8Bf_.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset133.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 10 },
    wordAnimation: {
      type: "scale",
      application: "active",
      mode: "dynamic",
      value: 1.1,
    },
  },
  {
    appearedColor: "#23292a",
    activeColor: "#23292a",
    activeFillColor: "transparent",
    color: "#23292a",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "CaveatBrush-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/caveatbrush/v6/EYq0maZfwr9S9-ETZc3fKXtMW7mT03pdQw.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset134.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 10 },
  },

  {
    appearedColor: "#fdf6eb",
    activeColor: "#fdf6eb",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "AguafinaScript-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/aguafinascript/v9/If2QXTv_ZzSxGIO30LemWEOmt1bHqs4pgicOrg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset135.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 10 },
    textTransform: "lowercase",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#000000",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "CabinCondensed-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/cabincondensed/v14/nwpJtK6mNhBK2err_hqkYhHRqmwi3Mf97F15-K1oqQ.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset136.webm",
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#fde400",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "DMSerifText-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/dmseriftext/v5/rnCu-xZa_krGokauCeNq1wWyafOPXHIJErY.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset137.webm",
    boxShadow: { color: "#fde400", x: 0, y: 0, blur: 30 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#ea3425",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Rubik-Black",
    fontUrl:
      "https://fonts.gstatic.com/s/rubik/v14/iJWZBXyIfDnIV5PNhY1KTN7Z-Yh-ro-1UE80V4bVkA.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset138.webm",
    boxShadow: { color: "#eb4d3d", x: 0, y: 0, blur: 60 },
    wordAnimation: {
      type: "scale",
      application: "active",
      mode: "static",
      value: 0.8,
    },
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "DMSerifText-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/dmseriftext/v5/rnCu-xZa_krGokauCeNq1wWyafOPXHIJErY.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset139.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    animation: "fadeByWord",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#b73226",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset140.webm",
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 10 },
    preservedColorKeyWord: true,
    wordAnimation: {
      type: "scale",
      application: "active",
      mode: "dynamic",
      value: 1.1,
    },
  },
  {
    appearedColor: "#fdc515",
    activeColor: "#fdc515",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#f5c944",
    borderWidth: 2,
    fontFamily: "DMSerifText-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/dmseriftext/v5/rnCu-xZa_krGokauCeNq1wWyafOPXHIJErY.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset141.webm",
    boxShadow: { color: "#fd6000", x: 2, y: 2, blur: 4 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff3a",
    backgroundColor: "rgba(10, 57, 146, 0.41)",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "DMSerifText-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/dmseriftext/v5/rnCu-xZa_krGokauCeNq1wWyafOPXHIJErY.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset142.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 30 },
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#0000d5",
    borderWidth: 7,
    fontFamily: "Inter-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset143.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 30 },
    textTransform: "uppercase",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#e7ef4e",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Chivo-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/chivo/v12/va9F4kzIxd1KFrjTZMZ_uqzGQC_-.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset144.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 30 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#ff0000",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Inter-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset145.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 30 },
    animation: "fadeByWord",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#5832e26c",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset146.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 30 },
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e12ff",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 2,
    fontFamily: "Staatliches-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/staatliches/v6/HI_OiY8KO6hCsQSoAPmtMbectJG9O9PS.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset147.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 30 },
    animation: ["slideLeftCaption", "fadeCaption"],
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#ff3a30",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    fontFamily: "Staatliches-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/staatliches/v6/HI_OiY8KO6hCsQSoAPmtMbectJG9O9PS.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset148.webm",
    boxShadow: { color: "#000000", x: 2, y: 2, blur: 30 },
    wordAnimation: {
      type: "scale",
      application: "active",
      mode: "static",
      value: 0.8,
    },
    preservedColorKeyWord: true,
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset149.webm",
    boxShadow: { color: "#000000", x: 3, y: 3, blur: 10 },
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e52f551",
    isKeywordColor: "#50ff12",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset150.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e12ff",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 2,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset151.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 30 },
    animation: ["slideLeftCaption", "fadeCaption"],
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e12ff",
    isKeywordColor: "#32c759",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "FredokaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fredokaone/v8/k3kUo8kEI-tA1RRcTZGmTmHBA6aF8Bf_.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset152.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    preservedColorKeyWord: true,
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 6,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset153.webm",
    boxShadow: { color: "#000000", x: 3, y: 3, blur: 10 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e12ff",
    isKeywordColor: "#d40001",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset154.webm",
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 10 },
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "FredokaOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/fredokaone/v8/k3kUo8kEI-tA1RRcTZGmTmHBA6aF8Bf_.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset156.webm",
    boxShadow: { color: "#412424", x: 0, y: 0, blur: 60 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#000000",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SecularOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/secularone/v5/8QINdiTajsj_87rMuMdKypDlMul7LJpK.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset157.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#5832e2",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Montserrat-ExtraBold",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_c5H7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset159.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#000000",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Montserrat-ExtraBold",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_c5H7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset160.webm",
    animation: "fadeCaption",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#c2c2c2",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 2,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset161.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 20 },
    textTransform: "uppercase",
    animation: "slideUpCaption",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#fcfd00",
    color: "#ffffff",
    backgroundColor: "#000000",
    borderColor: "#000000",
    borderWidth: 0,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset163.webm",
    textAlign: "left",
    animation: "slideLeftCaption",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "#7e12ff",
    borderColor: "#000000",
    borderWidth: 4,
    fontFamily: "JuliusSansOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/juliussansone/v9/1Pt2g8TAX_SGgBGUi0tGOYEga5W-xXEW6aGXHw.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset164.webm",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#000000",
    activeColor: "#000000",
    activeFillColor: "transparent",
    color: "#000000",
    backgroundColor: "#ffffff",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "JuliusSansOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/juliussansone/v9/1Pt2g8TAX_SGgBGUi0tGOYEga5W-xXEW6aGXHw.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset165.webm",
    textTransform: "uppercase",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e12ff",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset166.webm",
    boxShadow: { color: "#000000", x: 2, y: 2, blur: 10 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#000000",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset167.webm",
    textTransform: "uppercase",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#c2c2c2",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "CabinCondensed-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/cabincondensed/v14/nwpMtK6mNhBK2err_hqkYhHRqmwaYOjZ5HZl8Q.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset168.webm",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e12ff",
    isKeywordColor: "#50ff12",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SecularOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/secularone/v5/8QINdiTajsj_87rMuMdKypDlMul7LJpK.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset169.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 60 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "#000000",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Inter-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset170.webm",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#fcfd00",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset171.webm",
    boxShadow: { color: "#000000", x: 4, y: 4, blur: 25 },
    preservedColorKeyWord: true,
  },
  {
    type: "word",
    appearedColor: "#fcf400",
    activeColor: "#fcf400",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 8,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset173.webm",
    boxShadow: { color: "#000000", x: -4, y: 4, blur: 10 },
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 8,
    fontFamily: "Changa-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/changa/v14/2-c79JNi2YuVOUcOarRPgnNGooxCZ0q2QjDp9htf1ZM.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset175.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 40 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#00d870",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    fontFamily: "Bungee-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/bungee/v6/N0bU2SZBIuF2PU_ECn50Kd_PmA.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset179.webm",
    boxShadow: { color: "#000000", x: 3, y: 3, blur: 25 },
    textTransform: "uppercase",
    animation: "fadeByWord",
    preservedColorKeyWord: true,
    wordAnimation: {
      type: "scale",
      application: "active",
      mode: "dynamic",
      value: 1.2,
    },
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    fontFamily: "Changa-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/changa/v14/2-c79JNi2YuVOUcOarRPgnNGooxCZ0q2QjDp9htf1ZM.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset180.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 25 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#01c7fc",
    color: "#ffffff",
    backgroundColor: "#7e12ff",
    borderColor: "#000000",
    borderWidth: 2,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset182.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 20 },
    preservedColorKeyWord: true,
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Inter-Black",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuBWYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset184.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 20 },
    textTransform: "uppercase",
    animation: "fadeByWord",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 2,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset185.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    animation: "slideFadeByWord",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#000000",
    activeColor: "#000000",
    activeFillColor: "transparent",
    isKeywordColor: "#32c759",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset187.webm",
    textAlign: "left",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
  },
  {
    appearedColor: "#000000",
    activeColor: "#000000",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset188.webm",
    boxShadow: { color: "#000000", x: -4, y: 4, blur: 20 },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#ffcc02",
    color: "#ffffff",
    backgroundColor: "#000000",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Inter-SemiBold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset189.webm",
    textTransform: "uppercase",
    animation: "fadeCaption",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#ffcc02",
    color: "#ffffff",
    backgroundColor: "#000000",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Lobster-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/lobster/v23/neILzCirqoswsqX9_oWsMqEzSJQ.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset190.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    animation: "fadeByWord",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "#7e12ff",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Inter-SemiBold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset191.webm",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "#7e12ff",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "RobotoCondensed-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/robotocondensed/v19/ieVi2ZhZI2eCN5jzbjEETS9weq8-32meKCMSbvtdYyQ.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset192.webm",

    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#00d870",
    color: "transparent",
    backgroundColor: "#7e12ff",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Pacifico-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/pacifico/v17/FwZY7-Qmy14u9lezJ96A4sijpFu_.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset194.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    preservedColorKeyWord: true,
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e12ff",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SecularOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/secularone/v5/8QINdiTajsj_87rMuMdKypDlMul7LJpK.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset195.webm",
    boxShadow: { color: "#0e2beb", x: 0, y: 0, blur: 10 },
    textTransform: "uppercase",
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "#7e12ff",
    borderColor: "#000000",
    borderWidth: 2,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset197.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    animation: "fadeCaption",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#7e12ff",
    borderWidth: 8,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset198.webm",
    boxShadow: { color: "#7e12ff", x: 0, y: 0, blur: 50 },
    animation: "upLeftCaption",
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 2,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset199.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e12ff",
    isKeywordColor: "#50ff12",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 2,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset200.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#6c4df7",
    isKeywordColor: "#ffcc02",
    color: "#ffffff",
    backgroundColor: "#41434a",
    borderColor: "#000000",
    borderWidth: 2,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset201.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 30 },
    animation: "fadeByWord",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Staatliches-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/staatliches/v6/HI_OiY8KO6hCsQSoAPmtMbectJG9O9PS.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset202.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    animation: "fadeByWord",
    preservedColorKeyWord: true,
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#75fb4c",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset203.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    textTransform: "uppercase",
    animation: "fadeCaption",
  },
  {
    type: "word",
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#7e12ff",
    color: "#ffffff",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    fontFamily: "Montserrat-ExtraBold",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_c5H7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset204.webm",
    boxShadow: { color: "#000000", x: -4, y: 4, blur: 20 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "PlayfairDisplay-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/playfairdisplay/v25/nuFvD-vYSZviVYUb_rj3ij__anPXJzDwcbmjWBN2PKeiukDQZNLo_U2r.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset205.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 50 },
    textTransform: "uppercase",
    wordAnimation: {
      type: "opacity",
      application: "active",
      mode: "dynamic",
      value: 0.3,
    },
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#7e12ff",
    isKeywordColor: "#50ff12",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 4,
    fontFamily: "RobotoCondensed-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/robotocondensed/v19/ieVi2ZhZI2eCN5jzbjEETS9weq8-32meKCMSbvtdYyQ.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset206.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 20 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#ea3330",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "Rubik-Black",
    fontUrl:
      "https://fonts.gstatic.com/s/rubik/v14/iJWZBXyIfDnIV5PNhY1KTN7Z-Yh-ro-1UE80V4bVkA.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset207.webm",
    boxShadow: { color: "#474747", x: 0, y: 0, blur: 100 },
    textTransform: "uppercase",
    wordAnimation: {
      type: "opacity",
      application: "active",
      mode: "dynamic",
      value: 0.3,
    },
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#cdbffe",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Inter-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset208.webm",
    boxShadow: { color: "#474747", x: 0, y: 0, blur: 10 },
    textTransform: "uppercase",
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#50ff12",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset209.webm",
    boxShadow: { color: "#000000", x: -4, y: -4, blur: 25 },
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#39373a",
    activeColor: "#000000",
    activeFillColor: "transparent",
    color: "#39373a",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "Poppins-Bold",
    fontUrl:
      "https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7V1tvFP-KUEg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset210.webm",
    boxShadow: { color: "#474747", x: 0, y: 0, blur: 100 },
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ff5446",
    activeFillColor: "transparent",
    isKeywordColor: "#f2ed6b",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "Montserrat-Black",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_epG7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset211.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 15 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },

  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "#000000",
    isKeywordColor: "#ffcc02",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 0,
    fontFamily: "SigmarOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/sigmarone/v11/co3DmWZ8kjZuErj9Ta3dk6Pjp3Di8U0.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset212.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 8 },
    textTransform: "uppercase",
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#b9b1b1",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    isKeywordColor: "#ffffff",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    fontFamily: "Montserrat-Light",
    fontUrl:
      "https://fonts.gstatic.com/s/montserrat/v18/JTURjIg1_i6t8kCHKm45_cJD7g7J_950vCo.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset213.webm",
    boxShadow: { color: "#474747", x: 0, y: 0, blur: 10 },
    preservedColorKeyWord: true,
  },
  {
    appearedColor: "#ffffff",
    activeColor: "#ffffff",
    activeFillColor: "transparent",
    color: "transparent",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 10,
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset214.webm",
    boxShadow: { color: "#000000", x: 0, y: 0, blur: 10 },
    wordAnimation: {
      type: "opacity",
      application: "active",
      mode: "dynamic",
      value: 0.3,
    },
  },
  {
    type: "word",
    appearedColor: "#14edf8",
    activeColor: "#14edf8",
    activeFillColor: "transparent",
    color: "#14edf8",
    backgroundColor: "transparent",
    borderColor: "#000000",
    borderWidth: 5,
    fontFamily: "FrancoisOne-Regular",
    fontUrl:
      "https://fonts.gstatic.com/s/francoisone/v15/_Xmr-H4zszafZw3A-KPSZutNxgKQu_avAg.ttf",
    previewUrl:
      "https://cdn.designcombo.dev/caption_previews/dynamic-preset215.webm",
    wordAnimation: {
      type: "opacity",
      application: "active",
      mode: "dynamic",
      value: 0.7,
    },
  },
];
